//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaMurderGraduation.Web
{
    public partial class CharacterDossierPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlDossier;
        protected global::System.Web.UI.WebControls.Literal litScriptName;
        protected global::System.Web.UI.WebControls.Literal litCharacterName;
        protected global::System.Web.UI.WebControls.Literal litRoomName;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackRoom;
        protected global::System.Web.UI.WebControls.HyperLink lnkResult;
        protected global::System.Web.UI.WebControls.Literal litStageName;
        protected global::System.Web.UI.WebControls.Literal litGuideTitle;
        protected global::System.Web.UI.WebControls.Literal litGuideSummary;
        protected global::System.Web.UI.WebControls.Literal litReadyStatus;
        protected global::System.Web.UI.WebControls.Literal litRoleName;
        protected global::System.Web.UI.WebControls.Literal litCharacterDescription;
        protected global::System.Web.UI.WebControls.Literal litPlayerName;
        protected global::System.Web.UI.WebControls.Literal litPlayerCount;
        protected global::System.Web.UI.WebControls.Literal litGender;
        protected global::System.Web.UI.WebControls.Literal litAgeRange;
        protected global::System.Web.UI.WebControls.Literal litProfession;
        protected global::System.Web.UI.WebControls.Literal litPersonality;
        protected global::System.Web.UI.WebControls.Literal litSecretLine;
        protected global::System.Web.UI.WebControls.PlaceHolder phRolePdf;
        protected global::System.Web.UI.WebControls.Literal litRolePdfName;
        protected global::System.Web.UI.WebControls.HyperLink lnkRolePdf;
        protected global::System.Web.UI.WebControls.Repeater rptClues;
        protected global::System.Web.UI.WebControls.Repeater rptActionLogs;
        protected global::System.Web.UI.WebControls.Literal litRoomCode;
        protected global::System.Web.UI.WebControls.Literal litHostName;
        protected global::System.Web.UI.WebControls.Literal litReservationId;
        protected global::System.Web.UI.WebControls.Literal litSessionTime;
    }
}
