//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaMurderGraduation.Web
{
    public partial class DmDashboardPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlForbidden;
        protected global::System.Web.UI.WebControls.Panel pnlDashboard;
        protected global::System.Web.UI.WebControls.Literal litRoleName;
        protected global::System.Web.UI.WebControls.Literal litDmName;
        protected global::System.Web.UI.WebControls.Literal litSessionCount;
        protected global::System.Web.UI.WebControls.Literal litTodaySessionCount;
        protected global::System.Web.UI.WebControls.Literal litPendingAcceptCount;
        protected global::System.Web.UI.WebControls.Literal litActiveSessionCount;
        protected global::System.Web.UI.WebControls.Repeater rptScheduleDays;
        protected global::System.Web.UI.WebControls.Repeater rptTodaySessions;
        protected global::System.Web.UI.WebControls.Repeater rptChecklistSessions;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Repeater rptSessions;
    }
}
