//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaMurderGraduation.Web
{
    public partial class DownloadPage
    {
        protected global::System.Web.UI.WebControls.Repeater rptReleaseNotes;

        protected global::System.Web.UI.WebControls.Repeater rptDownloadOptions;
    }
}
