//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaMurderGraduation.Web
{
    public partial class GameResultPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Literal litScriptName;
        protected global::System.Web.UI.WebControls.Literal litRoomName;
        protected global::System.Web.UI.WebControls.Literal litHostName;
        protected global::System.Web.UI.WebControls.Literal litCurrentStage;
        protected global::System.Web.UI.WebControls.Literal litReservationId;
        protected global::System.Web.UI.WebControls.Literal litRoomCode;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackToRoom;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackToLobby;
        protected global::System.Web.UI.WebControls.Literal litResultBadge;
        protected global::System.Web.UI.WebControls.Literal litCorrectCharacterName;
        protected global::System.Web.UI.WebControls.Literal litTruthSummary;
        protected global::System.Web.UI.WebControls.Repeater rptVotes;
        protected global::System.Web.UI.WebControls.Repeater rptStages;
        protected global::System.Web.UI.WebControls.Repeater rptActionLogs;
        protected global::System.Web.UI.WebControls.Repeater rptAssignments;
    }
}
